// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0KDuqOczUokg4jQw81MheRsj6a4LXiEg',
    appId: '1:281067736574:web:d243d9b797478fd2bf44af',
    messagingSenderId: '281067736574',
    projectId: 'guard-suites',
    authDomain: 'guard-suites.firebaseapp.com',
    storageBucket: 'guard-suites.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuMhCrJZ7raQbuYB2BAXbVVK1LN9hW0Lc',
    appId: '1:281067736574:android:6b8ac0ad02c100c8bf44af',
    messagingSenderId: '281067736574',
    projectId: 'guard-suites',
    storageBucket: 'guard-suites.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqKve0Lq7HwOkb3OwXTEFtyhL18e92Pnw',
    appId: '1:281067736574:ios:15f4d4acd77f3443bf44af',
    messagingSenderId: '281067736574',
    projectId: 'guard-suites',
    storageBucket: 'guard-suites.appspot.com',
    iosClientId: '281067736574-pdjfed6saudok01sjmca863uas0chosi.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolmanagement',
  );
}
